
name: check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.9, '3.10']
        python-arch: [x86, x64]

        exclude:
          - os: ubuntu-latest
            python-arch: x86

          - os: macos-latest
            python-arch: x86

          - os: macos-latest
            python-version: '3.10'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}-${{ matrix.python-arch }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.python-arch }}

    - name: Upgrade pip & setuptools
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools

    - name: Install Test Dependencies
      run: |
        python -m pip install .[test]

    - name: Install Mesa x64
      if: ${{ matrix.os == 'windows-latest' && matrix.python-arch == 'x64' }}
      run: |
        curl.exe -L --output mesa.7z --url https://github.com/pal1000/mesa-dist-win/releases/download/21.2.5/mesa3d-21.2.5-release-msvc.7z
        "C:\Program Files\7-Zip\7z.exe" e mesa.7z x64
      shell: cmd

    - name: Install Mesa x86
      if: ${{ matrix.os == 'windows-latest' && matrix.python-arch == 'x86' }}
      run: |
        curl.exe -L --output mesa.7z --url https://github.com/pal1000/mesa-dist-win/releases/download/21.2.5/mesa3d-21.2.5-release-msvc.7z
        "C:\Program Files\7-Zip\7z.exe" e mesa.7z x86
      shell: cmd

    - name: Test (Ubuntu)
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        sudo apt-get install xvfb
        sudo modprobe uinput
        sudo chmod a+rw /dev/uinput
        sudo usermod -a -G input $USER
        sudo -u $USER env PATH=${PATH} xvfb-run -a python -m pytest --cov=gamut --cov-report=xml

    - name: Test (Windows)
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        set PATH=%cd%;%PATH%
        python -m pytest --cov=gamut --cov-report=xml
      shell: cmd

    - name: Test (Mac OS)
      if: ${{ matrix.os == 'macos-latest' }}
      run: |
        python -m pytest --cov=gamut --cov-report=xml

    - name: Codecov
      uses: codecov/codecov-action@v1.2.1

  static-analysis:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        architecture: x64

    - name: Upgrade pip & setuptools
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools

    - name: Install Pre-Commit
      run: |
        python -m pip install pre-commit

    - name: Static Analysis
      run: |
        python -m pre_commit run --all-files

