
name: check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.9, 3.10-dev]
        python-arch: [x86, x64]

        exclude:
          - os: ubuntu-latest
            python-arch: x86

          - os: macos-latest
            python-arch: x86

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}-${{ matrix.python-arch }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.python-arch }}

    - name: Upgrade pip & setuptools
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools

    - name: Install Test Dependencies
      run: |
        python -m pip install .[test]

    - name: Enable uinput for all users
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        sudo modprobe uinput
        sudo chmod a+rw /dev/uinput

    - name: Test
      uses: GabrielBB/xvfb-action@v1
      with:
        run: python -m pytest --cov=gamut --cov-report=xml -v

    - name: Codecov
      uses: codecov/codecov-action@v1.2.1

  static-analysis:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        architecture: x64

    - name: Upgrade pip & setuptools
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools

    - name: Install Pre-Commit
      run: |
        python -m pip install pre-commit

    - name: Static Analysis
      run: |
        python -m pre_commit run --all-files

